### ISSUE TITLE
GMA addon compatibility issues with Kodi 19+

### ISSUE THREAD

**Issue by jrm25** [cmik/plugin.video.gmatv#1]
Hello, I just want to say that the GMA addon is not allowing the install on matrix 19.0 I’m assuming because python version is at 2.25 while matrix is already at 3.0. So thought I would let you know:-) love the work with iwant tfc addon i love this better than the app that’s on google play.

**Comment by cmik** [comment]
Hi @jrm25 ,
The rework is still in progress. I'll let you know when a usable version is available.

**Comment by cmik** [comment]
@jrm25,
GMA.tv version [1.0.0](https://github.com/cmik/plugin.video.gmatv/releases/tag/v1.0.0) is released.
Your feedbacks are welcomed.
Thanks.
